# Generated by Django 3.2.18 on 2023-03-21 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid username', regex='^(?!.*\\.\\.)(?!.*\\.$)[^\\W][\\w.]{0,29}$')]),
        ),
    ]
