# Generated by Django 4.2 on 2023-04-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
