# Generated by Django 4.2 on 2023-04-19 07:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calorie_goal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='Nespecificat', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=6),
        ),
    ]
