# Generated by Django 4.2 on 2023-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_calorie_goal_user_gender_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
